[package]
name = "c_os"
version = "0.1.0"
authors = ["Christoph Wottawa <christoph.wottawa@me.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.4.0"

[package.metadata.bootimage]
default-target = "x86_64-c_os.json"